[project]
name = "SeeVoice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.3.2",
    "pycairo>=1.28.0",
    "tqdm>=4.67.1",
]
